export { AdapterRegistry, createDefaultRegistry } from './registry.js'
export { NextJsAdapter, nextJsAdapter } from './nextjs/index.js'
export { NuxtAdapter, nuxtAdapter } from './nuxt/index.js'
export { SvelteKitAdapter, svelteKitAdapter } from './sveltekit/index.js'
export { NestJsAdapter, nestJsAdapter } from './nestjs/index.js'
export { DjangoAdapter, djangoAdapter } from './django/index.js'
export { FastApiAdapter, fastApiAdapter } from './fastapi/index.js'
export { SpringBootAdapter, springBootAdapter } from './springboot/index.js'
export { setWasmDir } from './_shared/tree-sitter-loader.js'
export { extractFeCalls, extractFeCallsFromText, type FeCall } from './_shared/fe-call-extractor.js'
export { matchFeCallsToBeRoutes, remapCrossEdgeFromIds, type CrossGraphMatcherOpts } from './_shared/cross-graph-matcher.js'
